### PR TITLE
[BUG]: added tests to confirm the re-render of validation errors

### PR DESCRIPTION
**Pull request by toranb**
This will require some collaboration because I technically need a PR to land in ember-changeset first before we can get a green build here. That PR can be found [here](https://github.com/DockYard/ember-changeset/pull/157)

The full details about this bug can be found [here](https://github.com/DockYard/ember-changeset-validations/issues/127)

TL;DR 

The ember 1.13.13 support for this addon is broken when used in connection with ember-changeset because the errors are not truly cleared (visually) from the template itself. The only changes here are the test code to show that by example.

One questions about this PR - I had to bump the template compiler into dependencies (from devDependencies). Not certain why this isn't working without that change - open to improve that because I'd rather not impose that upon someone including this for pure validation workloads.

### CODE REVIEW

**Comment by poteto** [comment]
@toranb Could you also give this branch a try on your project to verify?

**Comment by toranb** [comment]
@poteto confirmed! using this in my package.json file was solid on ember 1.13.13 !

    `"ember-changeset-validations": "git@github.com:toranb/ember-changeset-validations.git#branches/fixEmber11313"`


thanks again for the speedy work! looking forward to a new release w/ improved ember 1.13 support!

**Comment by poteto** [comment]
Thank you for contributing!

**Comment by poteto** [comment]
Now in https://github.com/DockYard/ember-changeset-validations/releases/tag/v1.2.6

**Comment by toranb** [comment]
@poteto amazing! What speedy work! Thank you 100x !!!!

**Pull request merged**
