### PR TITLE
email validation fix

### PR DESCRIPTION
**Pull request by vinodhrajamuralidharan**
- [X] - existing validation rule accepts the email without domain (test@gmail) - So, I've updated the rule.

Closes # .

### CODE REVIEW

**Comment by brandynbennett** [comment]
Can you please add tests and update the documentation.

**Comment by poteto** [comment]
Hi, thanks for the PR. I would recommend creating your own email validator in your project instead. The reason for this is that I am uncertain what the entire range of valid emails is under this new regex, and I think front end validation of emails should be very light.

**Comment by gczene** [comment]
@poteto the current one is too open, e.g. 
- `email@domain`
-  'email@123' 
- `-@1`
are even accepted. Actually we had to provide our own regex (it is in this PR), but our suggestion with @vinodhrajamuralidharan to double check it .

Thanks

**Comment by poteto** [comment]
Please see https://github.com/DockYard/ember-changeset-validations/issues/120#issuecomment-281254061

**Pull request closed without merging**
